### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by rudijs** [gradeup/ckt-breaker#2]
Hi,

Using the latest nodejs v8, running the example code gives me:

```
(node:15020) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): I got nothing
(node:15020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will termina
te the Node.js process with a non-zero exit code.
```

I believe the example usage should be:

```
ckt.fire('Hello World').then(res => console.log('res',res)).catch(err => console.log('err',err))
```

Using the command line, with this update it works, but the script hangs and does not return:

```
err I got nothing
```

The setTimeout keeps the script running? I need to Ctrl-C (linux) to exit the script.

Thanks.

**Comment by niksrc** [comment]
Yes, there should be a catch block to handle promise rejections. The primary use case is for wrapping external services such as databases for long running servers. For CLI apps we have to manually exit using `process.exit(0)` as we don't remove any timers.
I have updated the readme to reflect these changes.

Thanks for taking the time out to open the issue 👍

**Comment by rudijs** [comment]
Ah OK .. cool got it :-)
